#!/usr/bin/env python3
import rospy
from std_msgs.msg import Empty, UInt8, Bool
from sensor_msgs.msg import Joy
from geometry_msgs.msg import Twist


class JoyState:
    def __init__(self):
        self.A = False
        self.B = False
        self.X = False
        self.Y = False
        self.LB = False
        self.RB = False
        self.View = False
        self.Menu = False
        self.Power = False
        self.LST = False
        self.RST = False
        self.LX = 0.  # +: left (Left Stick LR)
        self.LY = 0.  # +: top  (Left Stick FB)
        self.RX = 0.  # +: left
        self.RY = 0.  # +: top
        self.LT = 0.  # 1.0: idle, -1.0: depressed
        self.RT = 0.  # 1.0: idle, -1.0: depressed
        self.DX = 0.  # +: left (D pad)
        self.DY = 0.  # +: top (D pad)

    def parse_xbox_usb(self, msg):
        if len(msg.buttons) != 11 or len(msg.axes) != 8:
            raise ValueError('Invalid number of buttons (%d) or axes (%d)' % (
                len(msg.buttons), len(msg.axes)))
        self.A = msg.buttons[0]
        self.B = msg.buttons[1]
        self.X = msg.buttons[2]
        self.Y = msg.buttons[3]
        self.LB = msg.buttons[4]
        self.RB = msg.buttons[5]
        self.View = msg.buttons[6]
        self.Menu = msg.buttons[7]
        self.Power = msg.buttons[8]
        self.LST = msg.buttons[9]
        self.RST = msg.buttons[10]
        self.LX = msg.axes[0]
        self.LY = msg.axes[1]
        self.LT = msg.axes[2]
        self.RX = msg.axes[3]
        self.RY = msg.axes[4]
        self.RT = msg.axes[5]
        self.DX = msg.axes[6]
        self.DY = msg.axes[7]

    def parse(self, msg):
        err = None
        try:
            return self.parse_xbox_usb(msg)
        except ValueError as e:
            err = e
        raise err


class JoyTeleopNode:
    MAX_FLIP_DIR = 7

    def __init__(self):
        # Define parameters
        self.joy_state_prev = JoyState()
        # if None then not in agent mode, otherwise contains time of latest enable/ping
        self.agent_mode_t = None
        self.flip_dir = 0
        self.fast_mode = False

        # Start ROS node
        rospy.init_node('joy_teleop_node')

        # Load parameters
        self.agent_mode_timeout_sec = rospy.get_param(
            '~agent_mode_timeout_sec', 1.0)

        self.pub_takeoff = rospy.Publisher(
            'takeoff', Empty,  queue_size=1, latch=False)
        self.pub_manual_takeoff = rospy.Publisher(
            'manual_takeoff', Empty, queue_size=1, latch=False)
        self.pub_throw_takeoff = rospy.Publisher(
            'throw_takeoff', Empty,  queue_size=1, latch=False)
        self.pub_land = rospy.Publisher(
            'land', Empty,  queue_size=1, latch=False)
        self.pub_palm_land = rospy.Publisher(
            'palm_land', Empty,  queue_size=1, latch=False)
        self.pub_emergency = rospy.Publisher(
            'emergency', Empty,  queue_size=1, latch=False)
        self.pub_flattrim = rospy.Publisher(
            'flattrim', Empty,  queue_size=1, latch=False)
        self.pub_flip = rospy.Publisher(
            'flip', UInt8,  queue_size=1, latch=False)
        self.pub_cmd_out = rospy.Publisher(
            'cmd_vel', Twist, queue_size=10, latch=False)
        self.pub_fast_mode = rospy.Publisher(
            'fast_mode', Empty,  queue_size=1, latch=False)
        self.pub_video_mode = rospy.Publisher(
            'video_mode', Empty, queue_size=1, latch=False)
        self.sub_agent_cmd_in = rospy.Subscriber(
            'agent_cmd_vel_in', Twist, self.agent_cmd_cb)
        self.sub_joy = rospy.Subscriber('/joy', Joy, self.joy_cb)
        rospy.loginfo('Joystick teleop node initialized')

    def agent_cmd_cb(self, msg):
        if self.agent_mode_t is not None:
            # Check for idle timeout
            if (rospy.Time.now() - self.agent_mode_t).to_sec() > self.agent_mode_timeout_sec:
                self.agent_mode_t = None
            else:
                self.pub_cmd_out.publish(msg)

    def joy_cb(self, msg):
        self.joy_state = JoyState()
        self.joy_state.parse(msg)

        # Process emergency stop
        if not self.joy_state_prev.X and self.joy_state.X:
            self.pub_emergency.publish()
            #rospy.logwarn('Issued RESET')
            return

        # Process takeoff
        if not self.joy_state_prev.Menu and self.joy_state.Menu:
            self.pub_takeoff.publish()
            #rospy.logwarn('Issued TAKEOFF')

        # Process land
        if not self.joy_state_prev.View and self.joy_state.View:
            self.pub_land.publish()
            #rospy.logwarn('Issued LAND')

        # Process flat trim
        if not self.joy_state_prev.A and self.joy_state.A:
            self.pub_flattrim.publish()
            #rospy.logwarn('Issued FLATTRIM')
            
        # Process video mode
        if not self.joy_state_prev.Y and self.joy_state.Y:
            self.pub_video_mode.publish()
            #rospy.logwarn('Issued VIDEO_MODE')            

        # Process flip
        if not self.joy_state_prev.B and self.joy_state.B:
            self.pub_flip.publish(self.flip_dir)
            #rospy.logwarn('Issued FLIP %d' % self.flip_dir)
            self.flip_dir += 1
            if self.flip_dir > self.MAX_FLIP_DIR:
                self.flip_dir = 0

        # Update agent bypass mode
        if self.joy_state.LB:
            self.agent_mode_t = rospy.Time.now()
        else:
            self.agent_mode_t = None

        # Manual control mode
        if self.agent_mode_t is None:
            if not self.joy_state_prev.RB and self.joy_state.RB:                
                    self.pub_fast_mode.publish()

            cmd = Twist()
            cmd.linear.x = -self.joy_state.RY
            cmd.linear.y = self.joy_state.RX
            cmd.linear.z = self.joy_state.LY
            cmd.angular.z = -self.joy_state.LX
            self.pub_cmd_out.publish(cmd)

        # Copy to previous state
        self.joy_state_prev = self.joy_state

    def spin(self):
        rospy.spin()


if __name__ == '__main__':
    try:
        node = JoyTeleopNode()
        node.spin()
    except rospy.ROSInterruptException:
        pass
